### ISSUE TITLE
UnicodeSetAttribute sorts my set

### ISSUE THREAD

**Issue by mneil** [3mcloud/falcano#4]
I haven't confirmed with a test, however, from the code https://github.com/3mcloud/falcano/blob/master/falcano/attributes.py#L411 it seems as though my sets are being ordered. This would break certain scenarios.

- I have a queue
- the queue consists of UUIDs to identify the items in the queue
- I'm managing the queue via a set in dynamo
- I create the queue and save it

UUIDs can't be sorted and I really need the order to exist. But, my set is rearranged and the stored data in dynamo is not what I expected. I would process my queue out of order.

**Comment by erictwalker18** [comment]
I'm not convinced a set is a better way to manage the queue than a list. That being said, probably not a good idea to sort. Updated link: https://github.com/3mcloud/falcano/blob/dbf004defe68c228e866495df1cbfc11fc22dd8a/falcano/attributes.py#L414

**Comment by erictwalker18** [comment]
After a little research, dynamo will return the set in a random order that differs per request. I still agree it shouldn't be sorted, but do not manage an ordered data set with a set in dynamo.

**Comment by mneil** [comment]
🤔  good points. I see now that sets are not ordered, lists are https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/HowItWorks.NamingRulesDataTypes.html. So sorted here doesn't really affect anything. I wonder what the original intent was of sorted here then and what purpose it serves. Seems like extra computation for no reason.

**Comment by mneil** [comment]
Actually, no need to wonder. Pynamo https://github.com/pynamodb/PynamoDB/pull/151/files. This seems to exist entirely to facilitate testing (comparing lists that are sorted is easier). We definitely should remove that and optimize for usage performance, not ease of testing, if that is the real reason it exists.

**Comment by erictwalker18** [comment]
Yeah, it even coerces sets to lists, I fixed it here: https://github.com/3mcloud/falcano/pull/7
